const A=document.getElementById("admin");
async function me(){const r=await fetch("/api/admin/me");return r.ok}
function login(){A.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center"><div class="modalBox"><div class="brand"><span class="logo">🪔</span><span>Tyohar<span class="hub">Hub</span><small>Private Admin</small></span></div><h2>Admin Login</h2><div class="field"><label>Email</label><input id="email" value="admin@tyoharhub.in"></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password"></div><button class="btn premium" style="width:100%" onclick="doLogin()">Login</button><p id="err" class="muted"></p></div></main>`}
async function doLogin(){const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.getElementById("email").value,password:document.getElementById("password").value})});if(r.ok)dashboard();else document.getElementById("err").textContent="Invalid credentials."}
async function dashboard(){const [pr,or]=await Promise.all([fetch("/api/posters"),fetch("/api/admin/orders")]);if(pr.status===401){login();return}const data=await pr.json(),orders=or.ok?await or.json():[];A.innerHTML=`${nav()}<main class="section"><div class="container"><div class="sectionHead"><div><h1>Admin Dashboard</h1><p class="muted">Private control room — visitors cannot see this page.</p></div><button class="btn" onclick="logout()">Logout</button></div><div class="panel"><h3>Upload Poster</h3><div class="field"><label>Title</label><input id="title"></div><div class="field"><label>Festival</label><input id="festival" placeholder="Raksha Bandhan"></div><div class="field"><label>Price (₹, 0 = Free)</label><input id="price" type="number" min="0" value="0"></div><div class="field"><label>Description</label><input id="description"></div><div class="field"><label>Image</label><input id="image" type="file" accept="image/*"></div><button class="btn primary" onclick="addPoster()">Upload Poster</button></div><section class="section"><h2>Manage Posters</h2><div class="grid">${data.map(p=>`<article class="card"><img src="${p.image}"><div class="cardBody"><b>${escapeHtml(p.title)}</b><p class="muted">${escapeHtml(p.festival)}</p><div style="display:flex;gap:8px;align-items:center"><input id="price-${p.id}" type="number" min="0" value="${p.price}" style="max-width:110px"><button class="smallbtn" onclick="savePrice(${p.id})">Save ₹</button><button class="smallbtn" onclick="delPoster(${p.id})">Delete</button></div></div></article>`).join("")}</div></section><section class="section"><h2>Orders</h2><div class="panel">${orders.length?`<div class="tableWrap"><table><thead><tr><th>Order</th><th>Amount</th><th>Status</th><th>Email</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${escapeHtml(o.razorpay_order_id||("#"+o.id))}</td><td>₹${o.amount}</td><td>${escapeHtml(o.status)}</td><td>${escapeHtml(o.customer_email||"—")}</td></tr>`).join("")}</tbody></table></div>`:`<p class="muted">No orders yet.</p>`}</div></section></div></main>`}
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function nav(){return `<header class="nav"><div class="container navin"><a class="brand" href="/"><span class="logo">🪔</span><span>Tyohar<span class="hub">Hub</span><small>Private Admin Panel</small></span></a></div></header>`}
async function addPoster(){const fd=new FormData();fd.append("title",document.getElementById("title").value);fd.append("festival",document.getElementById("festival").value);fd.append("price",document.getElementById("price").value);fd.append("description",document.getElementById("description").value);const f=document.getElementById("image").files[0];if(f)fd.append("image",f);const r=await fetch("/api/admin/posters",{method:"POST",body:fd});if(r.ok)dashboard();else alert("Upload failed")}
async function savePrice(id){const value=document.getElementById(`price-${id}`).value;const r=await fetch(`/api/admin/posters/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({price:Number(value)})});if(r.ok)dashboard();else alert("Could not update price")}
async function delPoster(id){if(!confirm("Delete this poster?"))return;await fetch("/api/admin/posters/"+id,{method:"DELETE"});dashboard()}
async function logout(){await fetch("/api/admin/logout",{method:"POST"});login()}
me().then(ok=>ok?dashboard():login());
